<a href="https://colab.research.google.com/github/jamie07262/INFO-3608-PROJECT/blob/main/Clone.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import requests
import re

# Define GitHub paths
github_url = "https://github.com/jamie07262/INFO-3608-PROJECT/tree/main/data/raw"
raw_url_prefix = "https://raw.githubusercontent.com/jamie07262/INFO-3608-PROJECT/main/data/raw/"

# Get the HTML content of the folder
response = requests.get(github_url)
html = response.text

# Extract CSV filenames and remove duplicates
csv_files = list(set(re.findall(r'href=".*?/data/raw/([^"]+\.csv)"', html)))

# Create the directory and download the files
!mkdir -p raw
for file in csv_files:
    url = raw_url_prefix + file
    !wget -q -P raw {url}
    print(f"Downloaded: {file}")

print("All CSV files downloaded successfully.")

Downloaded: WNCAATourneySeeds.csv
Downloaded: MTeams.csv
Downloaded: MSecondaryTourneyCompactResults.csv
Downloaded: MNCAATourneySlots.csv
Downloaded: MMasseyOrdinalsPart1.csv
Downloaded: WNCAATourneyCompactResults.csv
Downloaded: WSeasons.csv
Downloaded: MNCAATourneySeedRoundSlots.csv
Downloaded: WTeamConferences.csv
Downloaded: MNCAATourneySeeds.csv
Downloaded: 538ratingsMen.csv
Downloaded: WGameCities.csv
Downloaded: WTeamSpellings.csv
Downloaded: MNCAATourneyDetailedResults.csv
Downloaded: SampleSubmissionStage2.csv
Downloaded: Conferences.csv
Downloaded: MTeamConferences.csv
Downloaded: MNCAATourneyCompactResults.csv
Downloaded: MSeasons.csv
Downloaded: Cities.csv
Downloaded: MRegularSeasonDetailedResults.csv
Downloaded: MMasseyOrdinalsPart2.csv
Downloaded: WRegularSeasonCompactResults.csv
Downloaded: MTeamCoaches.csv
Downloaded: WConferenceTourneyGames.csv
Downloaded: SeedBenchmarkStage1.csv
Downloaded: WNCAATourneyDetailedResults.csv
Downloaded: WSecondaryTourneyCompactResults.csv
Downloaded: WTeams.csv
Downloaded: MTeamSpellings.csv
Downloaded: WSecondaryTourneyTeams.csv
Downloaded: 538ratingsWomen.csv
Downloaded: MConferenceTourneyGames.csv
Downloaded: MSecondaryTourneyTeams.csv
Downloaded: SampleSubmissionStage1.csv
Downloaded: WNCAATourneySlots.csv
Downloaded: MGameCities.csv
Downloaded: MRegularSeasonCompactResults.csv
Downloaded: WRegularSeasonDetailedResults.csv
All CSV files downloaded successfully.

In [70]:
import numpy as np
from sklearn.datasets import load_iris
import pandas as pd
from IPython.display import display

In [71]:
#reading and concating men and women results and adding a new column to indicate the division

df_seeds = pd.concat(
    [
        pd.read_csv("raw/MNCAATourneySeeds.csv").assign(Divison="M"),
        pd.read_csv("raw/WNCAATourneySeeds.csv").assign(Divison="W"),
    ]
).reset_index(drop=True)

df_compact_season_results = pd.concat(
    [
        pd.read_csv("raw/MRegularSeasonCompactResults.csv").assign(Divison="M"),
        pd.read_csv("raw/WRegularSeasonCompactResults.csv").assign(Divison="W"),
    ]
).reset_index(drop=True)

df_compact_tourney_results = pd.concat(
    [
        pd.read_csv("raw/MNCAATourneyCompactResults.csv").assign(Divison="M"),
        pd.read_csv("raw/WNCAATourneyCompactResults.csv").assign(Divison="W"),
    ]
).reset_index(drop=True)

fivethiryeight_scores = pd.concat(
    [
        pd.read_csv("raw/538ratingsMen.csv").assign(Divison="M"),
        pd.read_csv("raw/538ratingsWomen.csv").assign(Divison="W"),
    ]
).reset_index(drop=True)


print("Seeds")
display(df_seeds)
print("Season Results")
display(df_compact_season_results)
print("Tournament Results")
display(df_compact_tourney_results)
print("538 Scores")
display(fivethiryeight_scores)

Seeds

      Season Seed  TeamID Divison
0       1985  W01    1207       M
1       1985  W02    1210       M
2       1985  W03    1228       M
3       1985  W04    1260       M
4       1985  W05    1374       M
...      ...  ...     ...     ...
4365    2025  Z12    3193       W
4366    2025  Z13    3251       W
4367    2025  Z14    3195       W
4368    2025  Z15    3117       W
4369    2025  Z16    3422       W

[4370 rows x 4 columns]

Season Results

        Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT Divison
0         1985      20     1228      81     1328      64    N      0       M
1         1985      25     1106      77     1354      70    H      0       M
2         1985      25     1112      63     1223      56    H      0       M
3         1985      25     1165      70     1432      54    H      0       M
4         1985      25     1192      86     1447      74    H      0       M
...        ...     ...      ...     ...      ...     ...  ...    ...     ...
329953    2025     131     3471      75     3413      66    A      0       W
329954    2025     132     3192      66     3476      49    H      0       W
329955    2025     132     3250      74     3119      62    H      0       W
329956    2025     132     3293      83     3125      62    N      0       W
329957    2025     132     3456      66     3144      63    N      0       W

[329958 rows x 9 columns]

Tournament Results

      Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT Divison
0       1985     136     1116      63     1234      54    N      0       M
1       1985     136     1120      59     1345      58    N      0       M
2       1985     136     1207      68     1250      43    N      0       M
3       1985     136     1229      58     1425      55    N      0       M
4       1985     136     1242      49     1325      38    N      0       M
...      ...     ...      ...     ...      ...     ...  ...    ...     ...
4163    2024     147     3163      80     3425      73    A      0       W
4164    2024     147     3234      94     3261      87    H      0       W
4165    2024     151     3234      71     3163      69    N      0       W
4166    2024     151     3376      78     3301      59    N      0       W
4167    2024     153     3376      87     3234      75    N      0       W

[4168 rows x 9 columns]

538 Scores

     Season  TeamID                TeamName  538rating Divison
0      2016    1242                  Kansas      94.46       M
1      2016    1314          North Carolina      93.94       M
2      2016    1438                Virginia      92.46       M
3      2016    1277          Michigan State      91.84       M
4      2016    1328                Oklahoma      89.96       M
..      ...     ...                     ...        ...     ...
927    2023    3368  Southeastern Louisiana      66.27       W
928    2023    3151             Chattanooga      64.87       W
929    2023    3284                Monmouth      64.10       W
930    2023    3380                Southern      61.73       W
931    2023    3357            Sacred Heart      59.94       W

[932 rows x 5 columns]

In [72]:
# Check for missing values and convert to DataFrame
missing_seeds = df_seeds.isnull().sum().reset_index()
missing_seeds.columns = ["Column", "Missing Values"]

missing_season_results = df_compact_season_results.isnull().sum().reset_index()
missing_season_results.columns = ["Column", "Missing Values"]

missing_tourney_results = df_compact_tourney_results.isnull().sum().reset_index()
missing_tourney_results.columns = ["Column", "Missing Values"]

missing_fivethiryeight_scores = fivethiryeight_scores.isnull().sum().reset_index()
missing_fivethiryeight_scores.columns = ["Column", "Missing Values"]

print("Seeds")
display(missing_seeds)
print("\n")
print("Season Results")
display(missing_season_results)
print("\n")
print("Tournament Results")
display(missing_tourney_results)
print("\n")
print("538 Scores")
display(missing_fivethiryeight_scores)

Seeds

    Column  Missing Values
0   Season               0
1     Seed               0
2   TeamID               0
3  Divison               0

Season Results

    Column  Missing Values
0   Season               0
1   DayNum               0
2  WTeamID               0
3   WScore               0
4  LTeamID               0
5   LScore               0
6     WLoc               0
7    NumOT               0
8  Divison               0

Tournament Results

    Column  Missing Values
0   Season               0
1   DayNum               0
2  WTeamID               0
3   WScore               0
4  LTeamID               0
5   LScore               0
6     WLoc               0
7    NumOT               0
8  Divison               0

538 Scores

      Column  Missing Values
0     Season               0
1     TeamID               0
2   TeamName               0
3  538rating               0
4    Divison               0

In [73]:
# Check for duplicates
duplicates_seeds = pd.DataFrame({"DataFrame": ["df_seeds"], "Duplicate Count": [df_seeds.duplicated().sum()]})
duplicates_season_results = pd.DataFrame({"DataFrame": ["df_compact_season_results"], "Duplicate Count": [df_compact_season_results.duplicated().sum()]})
duplicates_tourney_results = pd.DataFrame({"DataFrame": ["df_compact_tourney_results"], "Duplicate Count": [df_compact_tourney_results.duplicated().sum()]})
duplicates_fivethiryeight_scores = pd.DataFrame({"DataFrame": ["fivethiryeight_scores"], "Duplicate Count": [fivethiryeight_scores.duplicated().sum()]})

display(duplicates_seeds)
display(duplicates_season_results)
display(duplicates_tourney_results)
display(duplicates_fivethiryeight_scores)

  DataFrame  Duplicate Count
0  df_seeds                0

                   DataFrame  Duplicate Count
0  df_compact_season_results                0

                    DataFrame  Duplicate Count
0  df_compact_tourney_results                0

               DataFrame  Duplicate Count
0  fivethiryeight_scores                0

In [74]:
dtypes_seeds = df_seeds.dtypes.reset_index()
dtypes_seeds.columns = ["Column", "Data Type"]

dtypes_season_results = df_compact_season_results.dtypes.reset_index()
dtypes_season_results.columns = ["Column", "Data Type"]

dtypes_tourney_results = df_compact_tourney_results.dtypes.reset_index()
dtypes_tourney_results.columns = ["Column", "Data Type"]

dtypes_fivethiryeight_scores = fivethiryeight_scores.dtypes.reset_index()
dtypes_fivethiryeight_scores.columns = ["Column", "Data Type"]

print("Seeds")
display(dtypes_seeds)
print("\n")
print("Season Results")
display(dtypes_season_results)
print("\n")
print("Tournament Results")
display(dtypes_tourney_results)
print("\n")
print("538 Scores")
display(dtypes_fivethiryeight_scores)

Seeds

    Column Data Type
0   Season     int64
1     Seed    object
2   TeamID     int64
3  Divison    object

Season Results

    Column Data Type
0   Season     int64
1   DayNum     int64
2  WTeamID     int64
3   WScore     int64
4  LTeamID     int64
5   LScore     int64
6     WLoc    object
7    NumOT     int64
8  Divison    object

Tournament Results

    Column Data Type
0   Season     int64
1   DayNum     int64
2  WTeamID     int64
3   WScore     int64
4  LTeamID     int64
5   LScore     int64
6     WLoc    object
7    NumOT     int64
8  Divison    object

538 Scores

      Column Data Type
0     Season     int64
1     TeamID     int64
2   TeamName    object
3  538rating   float64
4    Divison    object

In [75]:
df_team_compact_season_results = pd.concat(
    [
        df_compact_season_results[["Season", "Divison", "WTeamID", "DayNum", "WScore", "LScore"]]
        .assign(Result="W")
        .rename(columns={"WTeamID": "TeamID", "WScore": "TeamScore", "LScore": "OpponentScore"}),

        df_compact_season_results[["Season", "Divison", "LTeamID", "DayNum", "WScore", "LScore"]]
        .assign(Result="L")
        .rename(columns={"LTeamID": "TeamID", "LScore": "TeamScore", "WScore": "OpponentScore"}),
    ]
).reset_index(drop=True)

In [76]:
df_team_compact_season_results

        Season Divison  TeamID  DayNum  TeamScore  OpponentScore Result
0         1985       M    1228      20         81             64      W
1         1985       M    1106      25         77             70      W
2         1985       M    1112      25         63             56      W
3         1985       M    1165      25         70             54      W
4         1985       M    1192      25         86             74      W
...        ...     ...     ...     ...        ...            ...    ...
659911    2025       W    3413     131         66             75      L
659912    2025       W    3476     132         49             66      L
659913    2025       W    3119     132         62             74      L
659914    2025       W    3125     132         62             83      L
659915    2025       W    3144     132         63             66      L

[659916 rows x 7 columns]

In [77]:
#caclulate and add score difference column
df_team_compact_season_results["ScoreDifference"] = df_team_compact_season_results["TeamScore"] - df_team_compact_season_results["OpponentScore"]

df_team_compact_season_results["Win"] = (df_team_compact_season_results["Result"] == "W").astype("int")

In [78]:
df_team_compact_season_results.sample(10, random_state=100)

,Season,Divison,TeamID,DayNum,TeamScore,OpponentScore,Result,ScoreDifference,Win
111081,2010,M,1363,80,87,76,W,11,1
599920,2014,W,3409,36,43,81,L,-38,0
432896,2009,M,1383,11,61,88,L,-27,0
269593,2014,W,3278,26,79,55,W,24,1
297303,2019,W,3129,72,75,74,W,1,1
408983,2004,M,1175,26,54,63,L,-9,0
539720,2001,W,3156,129,63,65,L,-2,0
260192,2012,W,3376,58,62,58,W,4,1
554715,2005,W,3395,48,55,82,L,-27,0
44009,1996,M,1343,28,62,45,W,17,1

In [79]:
#aggregate the data

agg_team_season = (
    df_team_compact_season_results.groupby(["Season", "TeamID", "Divison"])
    .agg(
        TeamScore=("TeamScore", "sum"),
        OpponentScore=("OpponentScore", "sum"),
        ScoreDifference=("ScoreDifference", "sum"),
        AverageScoreDifference=("ScoreDifference", "mean"),
        MedianScoreDifference=("ScoreDifference", "median"),
        MinScoreDifference=("ScoreDifference", "min"),
        MaxScoreDifference=("ScoreDifference", "max"),
        Wins=("Win", "sum"),
        Losses=("Result", lambda x: (x == "L").sum()),
        WinPercentage=("Win", "mean"),
    )
    .reset_index()
)

In [80]:
agg_team_season.sample(10, random_state=100)

,Season,TeamID,Divison,TeamScore,OpponentScore,ScoreDifference,AverageScoreDifference,MedianScoreDifference,MinScoreDifference,MaxScoreDifference,Wins,Losses,WinPercentage
1181,1989,1149,M,1791,1850,-59,-2.458333,-3.0,-35,20,8,16,0.333333
12007,2010,3132,W,2433,1984,449,13.606061,15.0,-19,35,27,6,0.818182
3914,1998,1199,M,2114,2048,66,2.200000,4.0,-48,38,17,13,0.566667
19911,2021,3388,W,1632,1859,-227,-8.730769,-9.5,-32,18,7,19,0.269231
16434,2016,3403,W,1963,2071,-108,-3.483871,-9.0,-39,62,13,18,0.419355
18843,2020,1358,M,2057,2021,36,1.333333,3.0,-16,20,14,13,0.518519
15678,2015,3347,W,1696,1796,-100,-3.448276,2.0,-36,24,17,12,0.586207
6360,2002,1143,M,2178,1992,186,6.200000,8.5,-46,33,22,8,0.733333
18715,2020,1227,M,2337,2335,2,0.058824,0.5,-46,34,17,17,0.500000
22658,2025,3254,W,1601,2025,-424,-14.133333,-11.5,-65,11,6,24,0.200000

In [81]:
# adding high seed column
# seed is the rank team's strength
df_seeds["HighSeed"] = (
    df_seeds["Seed"].str.replace("a", "").str.replace("b", "").str[1:].astype("int")
)

agg_team_season = agg_team_season.merge(
    df_seeds, on=["Season", "TeamID", "Divison"], how="left"
)

In [82]:
agg_team_season.sample(10, random_state=100)

,Season,TeamID,Divison,TeamScore,OpponentScore,ScoreDifference,AverageScoreDifference,MedianScoreDifference,MinScoreDifference,MaxScoreDifference,Wins,Losses,WinPercentage,Seed,HighSeed
1181,1989,1149,M,1791,1850,-59,-2.458333,-3.0,-35,20,8,16,0.333333,NaN,NaN
12007,2010,3132,W,2433,1984,449,13.606061,15.0,-19,35,27,6,0.818182,Y12,12.0
3914,1998,1199,M,2114,2048,66,2.200000,4.0,-48,38,17,13,0.566667,Y12,12.0
19911,2021,3388,W,1632,1859,-227,-8.730769,-9.5,-32,18,7,19,0.269231,NaN,NaN
16434,2016,3403,W,1963,2071,-108,-3.483871,-9.0,-39,62,13,18,0.419355,NaN,NaN
18843,2020,1358,M,2057,2021,36,1.333333,3.0,-16,20,14,13,0.518519,NaN,NaN
15678,2015,3347,W,1696,1796,-100,-3.448276,2.0,-36,24,17,12,0.586207,NaN,NaN
6360,2002,1143,M,2178,1992,186,6.200000,8.5,-46,33,22,8,0.733333,Y06,6.0
18715,2020,1227,M,2337,2335,2,0.058824,0.5,-46,34,17,17,0.500000,NaN,NaN
22658,2025,3254,W,1601,2025,-424,-14.133333,-11.5,-65,11,6,24,0.200000,NaN,NaN

In [83]:
df_team_tourney_results = pd.concat(
    [
        df_compact_tourney_results[
            ["Season", "Divison", "WTeamID", "LTeamID", "WScore", "LScore"]
        ]
        .assign(GameResult="W")
        .rename(
            columns={
                "WTeamID": "TeamID",
                "LTeamID": "OpponentTeamID",
                "WScore": "TeamScore",
                "LScore": "OpponentScore",
            }
        ),
        df_compact_tourney_results[
            ["Season", "Divison", "LTeamID", "WTeamID", "LScore", "WScore"]
        ]
        .assign(GameResult="L")
        .rename(
            columns={
                "LTeamID": "TeamID",
                "WTeamID": "OpponentTeamID",
                "LScore": "TeamScore",
                "WScore": "OpponentScore",
            }
        ),
    ]
).reset_index(drop=True)

df_team_tourney_results["Win"] = (df_team_tourney_results["GameResult"] == "W").astype(
    "int"
)

In [84]:
df_team_tourney_results.sample(10, random_state=100)

,Season,Divison,TeamID,OpponentTeamID,TeamScore,OpponentScore,GameResult,Win
7415,2009,W,3314,3345,70,85,L,0
1598,2010,M,1437,1352,73,70,W,1
2295,2021,M,1166,1325,72,58,W,1
1287,2005,M,1257,1418,68,62,W,1
3742,2017,W,3393,3235,85,65,W,1
4848,1995,M,1207,1314,64,74,L,0
7058,2003,W,3437,3397,49,73,L,0
5858,2011,M,1396,1361,64,71,L,0
1361,2006,M,1130,1285,69,56,W,1
5683,2008,M,1172,1242,57,59,L,0

In [85]:
df_historic_tourney_features = df_team_tourney_results.merge(
    agg_team_season[
        ["Season", "Divison", "TeamID", "WinPercentage", "MedianScoreDifference", "HighSeed"]
    ],
    on=["Season", "Divison", "TeamID"],
    how="left",
).merge(
    agg_team_season[
        ["Season", "Divison", "TeamID", "WinPercentage", "MedianScoreDifference", "HighSeed"]
    ].rename(
        columns={
            "TeamID": "OpponentTeamID",
            "WinPercentage": "OpponentWinPercentage",
            "MedianScoreDifference": "OpponentMedianScoreDifference",
            "HighSeed": "OpponentHighSeed",
        }
    ),
    on=["Season", "Divison", "OpponentTeamID"],
)

In [86]:
df_historic_tourney_features

,Season,Divison,TeamID,OpponentTeamID,TeamScore,OpponentScore,GameResult,Win,WinPercentage,MedianScoreDifference,HighSeed,OpponentWinPercentage,OpponentMedianScoreDifference,OpponentHighSeed
0,1985,M,1116,1234,63,54,W,1,0.636364,5.0,9.0,0.666667,9.5,8.0
1,1985,M,1120,1345,59,58,W,1,0.620690,2.0,11.0,0.680000,9.0,6.0
2,1985,M,1207,1250,68,43,W,1,0.925926,14.0,1.0,0.379310,-3.0,16.0
3,1985,M,1229,1425,58,55,W,1,0.740741,6.0,9.0,0.678571,2.5,8.0
4,1985,M,1242,1325,49,38,W,1,0.766667,5.5,3.0,0.740741,6.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8331,2024,W,3425,3163,73,80,L,0,0.838710,9.0,1.0,0.848485,26.0,3.0
8332,2024,W,3261,3234,87,94,L,0,0.848485,23.0,3.0,0.878788,23.0,1.0
8333,2024,W,3163,3234,69,71,L,0,0.848485,26.0,3.0,0.878788,23.0,1.0
8334,2024,W,3301,3376,59,78,L,0,0.818182,12.0,3.0,1.000000,26.0,1.0
8335,2024,W,3234,3376,75,87,L,0,0.878788,23.0,1.0,1.000000,26.0,1.0

In [87]:
df_historic_tourney_features["WinPercentageDifference"] = (
    df_historic_tourney_features["WinPercentage"]
    - df_historic_tourney_features["OpponentWinPercentage"]
)

df_historic_tourney_features["HighSeedDifference"] = (
    df_historic_tourney_features["HighSeed"]
    - df_historic_tourney_features["OpponentHighSeed"]
)

df_historic_tourney_features["MedianScoreDifferenceDifference"] = (
    df_historic_tourney_features["MedianScoreDifference"]
    - df_historic_tourney_features["OpponentMedianScoreDifference"]
)

In [88]:
df_historic_tourney_features.sample(10, random_state=100)

,Season,Divison,TeamID,OpponentTeamID,TeamScore,OpponentScore,GameResult,Win,WinPercentage,MedianScoreDifference,HighSeed,OpponentWinPercentage,OpponentMedianScoreDifference,OpponentHighSeed,WinPercentageDifference,HighSeedDifference,MedianScoreDifferenceDifference
7415,2009,W,3314,3345,70,85,L,0,0.812500,14.5,3.0,0.687500,11.0,6.0,0.125000,-3.0,3.5
1598,2010,M,1437,1352,73,70,W,1,0.774194,8.0,2.0,0.676471,5.5,15.0,0.097723,-13.0,2.5
2295,2021,M,1166,1325,72,58,W,1,0.714286,6.0,5.0,0.681818,9.0,13.0,0.032468,-8.0,-3.0
1287,2005,M,1257,1418,68,62,W,1,0.870968,15.0,4.0,0.655172,7.0,13.0,0.215795,-9.0,8.0
3742,2017,W,3393,3235,85,65,W,1,0.677419,16.0,8.0,0.600000,7.0,9.0,0.077419,-1.0,9.0
4848,1995,M,1207,1314,64,74,L,0,0.678571,4.5,6.0,0.827586,10.0,2.0,-0.149015,4.0,-5.5
7058,2003,W,3437,3397,49,73,L,0,0.833333,10.0,2.0,0.870968,16.0,1.0,-0.037634,1.0,-6.0
5858,2011,M,1396,1361,64,71,L,0,0.781250,9.5,7.0,0.937500,12.5,2.0,-0.156250,5.0,-3.0
1361,2006,M,1130,1285,69,56,W,1,0.781250,6.0,4.0,0.777778,6.0,12.0,0.003472,-8.0,0.0
5683,2008,M,1172,1242,57,59,L,0,0.806452,13.0,10.0,0.909091,19.0,1.0,-0.102639,9.0,-6.0

In [89]:
fivethiryeight_scores

     Season  TeamID                TeamName  538rating Divison
0      2016    1242                  Kansas      94.46       M
1      2016    1314          North Carolina      93.94       M
2      2016    1438                Virginia      92.46       M
3      2016    1277          Michigan State      91.84       M
4      2016    1328                Oklahoma      89.96       M
..      ...     ...                     ...        ...     ...
927    2023    3368  Southeastern Louisiana      66.27       W
928    2023    3151             Chattanooga      64.87       W
929    2023    3284                Monmouth      64.10       W
930    2023    3380                Southern      61.73       W
931    2023    3357            Sacred Heart      59.94       W

[932 rows x 5 columns]

In [90]:
df_historic_tourney_features = df_historic_tourney_features.merge(
    fivethiryeight_scores.drop("TeamName", axis=1),
    on=["Season", "Divison", "TeamID"],
    how="left",
).dropna(subset=["538rating"])

df_historic_tourney_features = df_historic_tourney_features.merge(
    fivethiryeight_scores.drop("TeamName", axis=1).rename(
        columns={"TeamID": "OpponentTeamID"}
    ),
    on=["Season", "Divison", "OpponentTeamID"],
    how="left",
    suffixes=("", "Opponent"),
)

In [91]:
df_historic_tourney_features.sample(10, random_state=100)

,Season,Divison,TeamID,OpponentTeamID,TeamScore,OpponentScore,GameResult,Win,WinPercentage,MedianScoreDifference,HighSeed,OpponentWinPercentage,OpponentMedianScoreDifference,OpponentHighSeed,WinPercentageDifference,HighSeedDifference,MedianScoreDifferenceDifference,538rating,538ratingOpponent
1130,2019,M,1125,1268,77,79,L,0,0.833333,12.5,11.0,0.687500,8.0,6.0,0.145833,5.0,4.5,81.74,84.82
969,2016,M,1268,1242,63,79,L,0,0.750000,6.5,5.0,0.878788,10.0,1.0,-0.128788,4.0,-3.5,87.37,94.46
1273,2022,M,1168,1181,61,78,L,0,0.655172,3.0,15.0,0.823529,11.5,2.0,-0.168357,13.0,-8.5,71.78,89.28
28,2016,M,1372,1452,70,56,W,1,0.821429,20.5,14.0,0.764706,11.0,3.0,0.056723,11.0,9.5,80.98,89.30
1292,2022,M,1350,1344,51,79,L,0,0.657143,5.0,12.0,0.833333,5.0,4.0,-0.176190,8.0,0.0,79.91,82.72
874,2023,W,3195,3450,74,63,W,1,0.909091,19.0,12.0,0.696970,7.0,5.0,0.212121,7.0,12.0,82.94,86.55
1080,2018,M,1252,1314,66,84,L,0,0.689655,7.0,15.0,0.714286,8.0,2.0,-0.024631,13.0,-1.0,72.45,90.62
1818,2023,W,3195,3437,57,76,L,0,0.909091,19.0,12.0,0.823529,13.0,4.0,0.085561,8.0,6.0,82.94,88.55
911,2023,W,3261,3274,54,42,W,1,0.933333,22.0,3.0,0.612903,5.0,9.0,0.320430,-6.0,17.0,96.14,83.49
1216,2021,M,1438,1325,58,62,L,0,0.750000,8.5,4.0,0.681818,9.0,13.0,0.068182,-9.0,-0.5,88.06,77.51

In [92]:
df_historic_tourney_features["538rating_Difference"] = (
    df_historic_tourney_features["538rating"]
    - df_historic_tourney_features["538ratingOpponent"]
)

In [93]:
df_historic_tourney_features.sample(10, random_state=100)

,Season,Divison,TeamID,OpponentTeamID,TeamScore,OpponentScore,GameResult,Win,WinPercentage,MedianScoreDifference,HighSeed,OpponentWinPercentage,OpponentMedianScoreDifference,OpponentHighSeed,WinPercentageDifference,HighSeedDifference,MedianScoreDifferenceDifference,538rating,538ratingOpponent,538rating_Difference
1130,2019,M,1125,1268,77,79,L,0,0.833333,12.5,11.0,0.687500,8.0,6.0,0.145833,5.0,4.5,81.74,84.82,-3.08
969,2016,M,1268,1242,63,79,L,0,0.750000,6.5,5.0,0.878788,10.0,1.0,-0.128788,4.0,-3.5,87.37,94.46,-7.09
1273,2022,M,1168,1181,61,78,L,0,0.655172,3.0,15.0,0.823529,11.5,2.0,-0.168357,13.0,-8.5,71.78,89.28,-17.50
28,2016,M,1372,1452,70,56,W,1,0.821429,20.5,14.0,0.764706,11.0,3.0,0.056723,11.0,9.5,80.98,89.30,-8.32
1292,2022,M,1350,1344,51,79,L,0,0.657143,5.0,12.0,0.833333,5.0,4.0,-0.176190,8.0,0.0,79.91,82.72,-2.81
874,2023,W,3195,3450,74,63,W,1,0.909091,19.0,12.0,0.696970,7.0,5.0,0.212121,7.0,12.0,82.94,86.55,-3.61
1080,2018,M,1252,1314,66,84,L,0,0.689655,7.0,15.0,0.714286,8.0,2.0,-0.024631,13.0,-1.0,72.45,90.62,-18.17
1818,2023,W,3195,3437,57,76,L,0,0.909091,19.0,12.0,0.823529,13.0,4.0,0.085561,8.0,6.0,82.94,88.55,-5.61
911,2023,W,3261,3274,54,42,W,1,0.933333,22.0,3.0,0.612903,5.0,9.0,0.320430,-6.0,17.0,96.14,83.49,12.65
1216,2021,M,1438,1325,58,62,L,0,0.750000,8.5,4.0,0.681818,9.0,13.0,0.068182,-9.0,-0.5,88.06,77.51,10.55

In [94]:

df_historic_tourney_features[["Season", "TeamID", "538rating", "538ratingOpponent", "538rating_Difference"]].sample(10, random_state=100)

      Season  TeamID  538rating  538ratingOpponent  538rating_Difference
1130    2019    1125      81.74              84.82                 -3.08
969     2016    1268      87.37              94.46                 -7.09
1273    2022    1168      71.78              89.28                -17.50
28      2016    1372      80.98              89.30                 -8.32
1292    2022    1350      79.91              82.72                 -2.81
874     2023    3195      82.94              86.55                 -3.61
1080    2018    1252      72.45              90.62                -18.17
1818    2023    3195      82.94              88.55                 -5.61
911     2023    3261      96.14              83.49                 12.65
1216    2021    1438      88.06              77.51                 10.55

In [95]:
df_historic_tourney_features.head()

,Season,Divison,TeamID,OpponentTeamID,TeamScore,OpponentScore,GameResult,Win,WinPercentage,MedianScoreDifference,HighSeed,OpponentWinPercentage,OpponentMedianScoreDifference,OpponentHighSeed,WinPercentageDifference,HighSeedDifference,MedianScoreDifferenceDifference,538rating,538ratingOpponent,538rating_Difference
0,2016,M,1195,1192,96,65,W,1,0.551724,2.0,16.0,0.548387,2.0,16.0,0.003337,0.0,0.0,71.41,66.72,4.69
1,2016,M,1455,1435,70,50,W,1,0.741935,17.0,11.0,0.593750,10.0,11.0,0.148185,0.0,7.0,86.59,85.59,1.00
2,2016,M,1221,1380,59,55,W,1,0.424242,-4.0,16.0,0.612903,4.0,16.0,-0.188661,0.0,-8.0,66.85,67.96,-1.11
3,2016,M,1276,1409,67,62,W,1,0.636364,5.0,11.0,0.645161,8.0,11.0,-0.008798,0.0,-3.0,79.57,79.93,-0.36
4,2016,M,1114,1345,85,83,W,1,0.870968,8.0,12.0,0.764706,13.0,5.0,0.106262,7.0,-5.0,78.90,88.68,-9.78

In [96]:
df_historic_tourney_features["BaselinePred"] = (
    df_historic_tourney_features["HighSeed"]
    < df_historic_tourney_features["OpponentHighSeed"]
)

df_historic_tourney_features.loc[
    df_historic_tourney_features["HighSeed"]
    == df_historic_tourney_features["OpponentHighSeed"],
    "BaselinePred",
] = (
    df_historic_tourney_features["WinPercentage"]
    > df_historic_tourney_features["OpponentWinPercentage"]
)

In [97]:
from sklearn.metrics import accuracy_score, log_loss
cv_scores_baseline = []
for season in df_historic_tourney_features["Season"].unique():
    pred = df_historic_tourney_features.query("Season == @season")[
        "BaselinePred"
    ].astype("int")
    y = df_historic_tourney_features.query("Season == @season")["Win"]
    score = accuracy_score(y, pred)
    score_ll = log_loss(y, pred)
    cv_scores_baseline.append(score)
    print(f"Holdout season {season} - Accuracy {score:0.4f} Log Loss {score_ll:0.4f}")

print(f"Baseline accuracy {np.mean(cv_scores_baseline):0.4f}")

Holdout season 2016 - Accuracy 0.6846 Log Loss 11.3676
Holdout season 2017 - Accuracy 0.7769 Log Loss 8.0405
Holdout season 2018 - Accuracy 0.7000 Log Loss 10.8131
Holdout season 2019 - Accuracy 0.7538 Log Loss 8.8723
Holdout season 2021 - Accuracy 0.7519 Log Loss 8.9411
Holdout season 2022 - Accuracy 0.7015 Log Loss 10.7593
Holdout season 2023 - Accuracy 0.7164 Log Loss 10.2213
Baseline accuracy 0.7265

In [98]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import matplotlib as mpl
from matplotlib.patches import Circle, Rectangle, Arc
import seaborn as sns

from sklearn.metrics import accuracy_score, log_loss
import xgboost as xgb
from sklearn.model_selection import GroupKFold

FEATURES = [
    #     "WinPercentage",
    #     "MedianScoreDiff",
    #     "ChalkSeed",
    #     "OppWinPercentage",
    #     "OppMedianScoreDiff",
    #     "OppChalkSeed",
    #     "538rating",
    #     "538ratingOpp",
    "WinPercentageDifference",
    "HighSeedDifference",
    "538rating_Difference",
]
TARGET = "Win"


X = df_historic_tourney_features[FEATURES]
y = df_historic_tourney_features[TARGET]
groups = df_historic_tourney_features["Season"]
seasons = df_historic_tourney_features["Season"].unique()

# Setup cross-validation
gkf = GroupKFold(n_splits=df_historic_tourney_features["Season"].nunique())
cv_results = []
models = []

season_idx = 0
for train_index, test_index in gkf.split(X, y, groups):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    # Prepare the model
    model = xgb.XGBRegressor(
        eval_metric="logloss",
        n_estimators=1_000,
        learning_rate=0.001,
    )
    holdout_season = seasons[season_idx]
    print(f"Holdout Season: {holdout_season}")
    # Train the model
    model.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=100)

    # Predict on the test set
    y_pred = model.predict(X_test)
    score_ll = log_loss(y_test, y_pred)
    y_pred = y_pred > 0.5
    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    cv_results.append(accuracy)
    season_idx += 1
    print(f"Season {holdout_season}: {accuracy} {score_ll}")
    models.append(model)
# Print the average accuracy across all folds
print("Average CV Accuracy:", np.mean(cv_results))

Holdout Season: 2016
[0]	validation_0-logloss:0.69287
[100]	validation_0-logloss:0.66825
[200]	validation_0-logloss:0.64908
[300]	validation_0-logloss:0.63335
[400]	validation_0-logloss:0.61986
[500]	validation_0-logloss:0.60935
[600]	validation_0-logloss:0.59996
[700]	validation_0-logloss:0.59197
[800]	validation_0-logloss:0.58747
[900]	validation_0-logloss:0.58413
[999]	validation_0-logloss:0.58217
Season 2016: 0.7014925373134329 0.5821676845927165
Holdout Season: 2017
[0]	validation_0-logloss:0.69285
[100]	validation_0-logloss:0.66734
[200]	validation_0-logloss:0.64666
[300]	validation_0-logloss:0.62948
[400]	validation_0-logloss:0.61425
[500]	validation_0-logloss:0.60199
[600]	validation_0-logloss:0.59198
[700]	validation_0-logloss:0.58352
[800]	validation_0-logloss:0.57615
[900]	validation_0-logloss:0.56981
[999]	validation_0-logloss:0.56473
Season 2017: 0.7089552238805971 0.5647296910413034
Holdout Season: 2018
[0]	validation_0-logloss:0.69275
[100]	validation_0-logloss:0.65695
[200]	validation_0-logloss:0.62721
[300]	validation_0-logloss:0.60206
[400]	validation_0-logloss:0.58106
[500]	validation_0-logloss:0.56345
[600]	validation_0-logloss:0.54777
[700]	validation_0-logloss:0.53394
[800]	validation_0-logloss:0.52229
[900]	validation_0-logloss:0.51213
[999]	validation_0-logloss:0.50291
Season 2018: 0.7769230769230769 0.5029074829145611
Holdout Season: 2019
[0]	validation_0-logloss:0.69278
[100]	validation_0-logloss:0.66024
[200]	validation_0-logloss:0.63480
[300]	validation_0-logloss:0.61132
[400]	validation_0-logloss:0.59130
[500]	validation_0-logloss:0.57301
[600]	validation_0-logloss:0.55748
[700]	validation_0-logloss:0.54483
[800]	validation_0-logloss:0.53382
[900]	validation_0-logloss:0.52413
[999]	validation_0-logloss:0.51587
Season 2019: 0.7730769230769231 0.5158732115246313
Holdout Season: 2021
[0]	validation_0-logloss:0.69284
[100]	validation_0-logloss:0.66491
[200]	validation_0-logloss:0.64282
[300]	validation_0-logloss:0.62552
[400]	validation_0-logloss:0.61153
[500]	validation_0-logloss:0.59908
[600]	validation_0-logloss:0.58810
[700]	validation_0-logloss:0.58011
[800]	validation_0-logloss:0.57398
[900]	validation_0-logloss:0.56887
[999]	validation_0-logloss:0.56494
Season 2021: 0.7038461538461539 0.5649389382668245
Holdout Season: 2022
[0]	validation_0-logloss:0.69281
[100]	validation_0-logloss:0.66311
[200]	validation_0-logloss:0.63946
[300]	validation_0-logloss:0.62023
[400]	validation_0-logloss:0.60376
[500]	validation_0-logloss:0.59038
[600]	validation_0-logloss:0.58031
[700]	validation_0-logloss:0.57217
[800]	validation_0-logloss:0.56606
[900]	validation_0-logloss:0.56063
[999]	validation_0-logloss:0.55519
Season 2022: 0.7423076923076923 0.5551933040161838
Holdout Season: 2023
[0]	validation_0-logloss:0.69283
[100]	validation_0-logloss:0.66425
[200]	validation_0-logloss:0.64130
[300]	validation_0-logloss:0.62233
[400]	validation_0-logloss:0.60713
[500]	validation_0-logloss:0.59424
[600]	validation_0-logloss:0.58236
[700]	validation_0-logloss:0.57309
[800]	validation_0-logloss:0.56587
[900]	validation_0-logloss:0.55933
[999]	validation_0-logloss:0.55456
Season 2023: 0.7286821705426356 0.5545604091564248
Average CV Accuracy: 0.7336119682700731