<a href="https://colab.research.google.com/github/jamie07262/INFO-3608-PROJECT/blob/main/Data_Processor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [107]:
import requests
import re

# Define GitHub repository and raw file URL structure
github_url = "https://github.com/jamie07262/INFO-3608-PROJECT/tree/main/data/raw"
raw_url_prefix = "https://raw.githubusercontent.com/jamie07262/INFO-3608-PROJECT/main/data/raw/"

# Request the HTML content of the raw data folder
response = requests.get(github_url)
html = response.text

# Extract all CSV filenames from the HTML using regex and remove duplicates
csv_files = list(set(re.findall(r'href=".*?/data/raw/([^"]+\.csv)"', html)))

# Create local 'raw' directory and download each CSV file
!mkdir -p raw
for file in csv_files:
    url = raw_url_prefix + file
    !wget -q -P raw {url}
    print(f"Downloaded: {file}")

print("All CSV files have been downloaded successfully.")

Downloaded: Cities.csv
Downloaded: WNCAATourneySeeds.csv
Downloaded: MSecondaryTourneyCompactResults.csv
Downloaded: MConferenceTourneyGames.csv
Downloaded: MSecondaryTourneyTeams.csv
Downloaded: MTeams.csv
Downloaded: MNCAATourneySlots.csv
Downloaded: MMasseyOrdinalsPart1.csv
Downloaded: MMasseyOrdinalsPart2.csv
Downloaded: 538ratingsWomen.csv
Downloaded: 538ratingsMen.csv
Downloaded: WTeamSpellings.csv
Downloaded: MNCAATourneySeeds.csv
Downloaded: MSeasons.csv
Downloaded: MTeamSpellings.csv
Downloaded: WSecondaryTourneyCompactResults.csv
Downloaded: WNCAATourneyCompactResults.csv
Downloaded: MGameCities.csv
Downloaded: MRegularSeasonDetailedResults.csv
Downloaded: WSecondaryTourneyTeams.csv
Downloaded: WRegularSeasonCompactResults.csv
Downloaded: WNCAATourneyDetailedResults.csv
Downloaded: WNCAATourneySlots.csv
Downloaded: SampleSubmissionStage1.csv
Downloaded: WTeams.csv
Downloaded: WTeamConferences.csv
Downloaded: MNCAATourneySeedRoundSlots.csv
Downloaded: WGameCities.csv
Downloaded: MNCAATourneyDetailedResults.csv
Downloaded: MTeamCoaches.csv
Downloaded: SampleSubmissionStage2.csv
Downloaded: SeedBenchmarkStage1.csv
Downloaded: MNCAATourneyCompactResults.csv
Downloaded: Conferences.csv
Downloaded: WSeasons.csv
Downloaded: WRegularSeasonDetailedResults.csv
Downloaded: MRegularSeasonCompactResults.csv
Downloaded: WConferenceTourneyGames.csv
Downloaded: MTeamConferences.csv
All CSV files have been downloaded successfully.

In [108]:
# Standard libraries for data analysis and display
import numpy as np
import pandas as pd
from IPython.display import display

In [109]:
# Read and combine data for tournament seeds, regular season results, tournament results, and 538 ratings
# Add Division column to indicate the division (M for men's, W for women's)

df_seeds = pd.concat(
    [
        pd.read_csv("raw/MNCAATourneySeeds.csv").assign(Divison="M"),
        pd.read_csv("raw/WNCAATourneySeeds.csv").assign(Divison="W"),
    ]
).reset_index(drop=True)

df_compact_season_results = pd.concat(
    [
        pd.read_csv("raw/MRegularSeasonCompactResults.csv").assign(Divison="M"),
        pd.read_csv("raw/WRegularSeasonCompactResults.csv").assign(Divison="W"),
    ]
).reset_index(drop=True)

df_compact_tourney_results = pd.concat(
    [
        pd.read_csv("raw/MNCAATourneyCompactResults.csv").assign(Divison="M"),
        pd.read_csv("raw/WNCAATourneyCompactResults.csv").assign(Divison="W"),
    ]
).reset_index(drop=True)

fivethiryeight_scores = pd.concat(
    [
        pd.read_csv("raw/538ratingsMen.csv").assign(Divison="M"),
        pd.read_csv("raw/538ratingsWomen.csv").assign(Divison="W"),
    ]
).reset_index(drop=True)


# Display the concatenated DataFrames
display(df_seeds)
print("Season Results")
display(df_compact_season_results)
print("Tournament Results")
display(df_compact_tourney_results)
print("538 Scores")
display(fivethiryeight_scores)

      Season Seed  TeamID Divison
0       1985  W01    1207       M
1       1985  W02    1210       M
2       1985  W03    1228       M
3       1985  W04    1260       M
4       1985  W05    1374       M
...      ...  ...     ...     ...
4365    2025  Z12    3193       W
4366    2025  Z13    3251       W
4367    2025  Z14    3195       W
4368    2025  Z15    3117       W
4369    2025  Z16    3422       W

[4370 rows x 4 columns]

Season Results

        Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT Divison
0         1985      20     1228      81     1328      64    N      0       M
1         1985      25     1106      77     1354      70    H      0       M
2         1985      25     1112      63     1223      56    H      0       M
3         1985      25     1165      70     1432      54    H      0       M
4         1985      25     1192      86     1447      74    H      0       M
...        ...     ...      ...     ...      ...     ...  ...    ...     ...
329953    2025     131     3471      75     3413      66    A      0       W
329954    2025     132     3192      66     3476      49    H      0       W
329955    2025     132     3250      74     3119      62    H      0       W
329956    2025     132     3293      83     3125      62    N      0       W
329957    2025     132     3456      66     3144      63    N      0       W

[329958 rows x 9 columns]

Tournament Results

      Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT Divison
0       1985     136     1116      63     1234      54    N      0       M
1       1985     136     1120      59     1345      58    N      0       M
2       1985     136     1207      68     1250      43    N      0       M
3       1985     136     1229      58     1425      55    N      0       M
4       1985     136     1242      49     1325      38    N      0       M
...      ...     ...      ...     ...      ...     ...  ...    ...     ...
4163    2024     147     3163      80     3425      73    A      0       W
4164    2024     147     3234      94     3261      87    H      0       W
4165    2024     151     3234      71     3163      69    N      0       W
4166    2024     151     3376      78     3301      59    N      0       W
4167    2024     153     3376      87     3234      75    N      0       W

[4168 rows x 9 columns]

538 Scores

     Season  TeamID                TeamName  538rating Divison
0      2016    1242                  Kansas      94.46       M
1      2016    1314          North Carolina      93.94       M
2      2016    1438                Virginia      92.46       M
3      2016    1277          Michigan State      91.84       M
4      2016    1328                Oklahoma      89.96       M
..      ...     ...                     ...        ...     ...
927    2023    3368  Southeastern Louisiana      66.27       W
928    2023    3151             Chattanooga      64.87       W
929    2023    3284                Monmouth      64.10       W
930    2023    3380                Southern      61.73       W
931    2023    3357            Sacred Heart      59.94       W

[932 rows x 5 columns]

In [110]:
# Check for missing values in each DataFrame and convert the result into a DataFrame with column names for clarity
missing_seeds = df_seeds.isnull().sum().reset_index()
missing_seeds.columns = ["Column", "Missing Values"]

missing_season_results = df_compact_season_results.isnull().sum().reset_index()
missing_season_results.columns = ["Column", "Missing Values"]

missing_tourney_results = df_compact_tourney_results.isnull().sum().reset_index()
missing_tourney_results.columns = ["Column", "Missing Values"]

missing_fivethiryeight_scores = fivethiryeight_scores.isnull().sum().reset_index()
missing_fivethiryeight_scores.columns = ["Column", "Missing Values"]

# Display the missing values for each dataset to check for completeness
print("Seeds")
display(missing_seeds)
print("\n")
print("Season Results")
display(missing_season_results)
print("\n")
print("Tournament Results")
display(missing_tourney_results)
print("\n")
print("538 Scores")
display(missing_fivethiryeight_scores)

Seeds

    Column  Missing Values
0   Season               0
1     Seed               0
2   TeamID               0
3  Divison               0

Season Results

    Column  Missing Values
0   Season               0
1   DayNum               0
2  WTeamID               0
3   WScore               0
4  LTeamID               0
5   LScore               0
6     WLoc               0
7    NumOT               0
8  Divison               0

Tournament Results

    Column  Missing Values
0   Season               0
1   DayNum               0
2  WTeamID               0
3   WScore               0
4  LTeamID               0
5   LScore               0
6     WLoc               0
7    NumOT               0
8  Divison               0

538 Scores

      Column  Missing Values
0     Season               0
1     TeamID               0
2   TeamName               0
3  538rating               0
4    Divison               0

In [111]:
# Check for duplicates in each DataFrame and count the number of duplicated rows
duplicates_seeds = pd.DataFrame({
    "DataFrame": ["df_seeds"],
    "Duplicate Count": [df_seeds.duplicated().sum()]
})

duplicates_season_results = pd.DataFrame({
    "DataFrame": ["df_compact_season_results"],
    "Duplicate Count": [df_compact_season_results.duplicated().sum()]
})

duplicates_tourney_results = pd.DataFrame({
    "DataFrame": ["df_compact_tourney_results"],
    "Duplicate Count": [df_compact_tourney_results.duplicated().sum()]
})

duplicates_fivethiryeight_scores = pd.DataFrame({
    "DataFrame": ["fivethiryeight_scores"],
    "Duplicate Count": [fivethiryeight_scores.duplicated().sum()]
})

# Display the duplicate counts for each dataset to inspect whether any duplicates exist
display(duplicates_seeds)
display(duplicates_season_results)
display(duplicates_tourney_results)
display(duplicates_fivethiryeight_scores)

  DataFrame  Duplicate Count
0  df_seeds                0

                   DataFrame  Duplicate Count
0  df_compact_season_results                0

                    DataFrame  Duplicate Count
0  df_compact_tourney_results                0

               DataFrame  Duplicate Count
0  fivethiryeight_scores                0

In [112]:
# Get the data types for each DataFrame's columns
dtypes_seeds = df_seeds.dtypes.reset_index()
dtypes_seeds.columns = ["Column", "Data Type"]

dtypes_season_results = df_compact_season_results.dtypes.reset_index()
dtypes_season_results.columns = ["Column", "Data Type"]

dtypes_tourney_results = df_compact_tourney_results.dtypes.reset_index()
dtypes_tourney_results.columns = ["Column", "Data Type"]

dtypes_fivethiryeight_scores = fivethiryeight_scores.dtypes.reset_index()
dtypes_fivethiryeight_scores.columns = ["Column", "Data Type"]

# Display the data types of each dataset
print("Seeds")
display(dtypes_seeds)
print("\n")
print("Season Results")
display(dtypes_season_results)
print("\n")
print("Tournament Results")
display(dtypes_tourney_results)
print("\n")
print("538 Scores")
display(dtypes_fivethiryeight_scores)

Seeds

    Column Data Type
0   Season     int64
1     Seed    object
2   TeamID     int64
3  Divison    object

Season Results

    Column Data Type
0   Season     int64
1   DayNum     int64
2  WTeamID     int64
3   WScore     int64
4  LTeamID     int64
5   LScore     int64
6     WLoc    object
7    NumOT     int64
8  Divison    object

Tournament Results

    Column Data Type
0   Season     int64
1   DayNum     int64
2  WTeamID     int64
3   WScore     int64
4  LTeamID     int64
5   LScore     int64
6     WLoc    object
7    NumOT     int64
8  Divison    object

538 Scores

      Column Data Type
0     Season     int64
1     TeamID     int64
2   TeamName    object
3  538rating   float64
4    Divison    object

In [113]:
# Combine the season results for both the winning and losing teams into a single DataFrame
df_team_compact_season_results = pd.concat(
    [
        df_compact_season_results[["Season", "Divison", "WTeamID", "DayNum", "WScore", "LScore"]]
        .assign(Result="W")
        .rename(columns={"WTeamID": "TeamID", "WScore": "TeamScore", "LScore": "OpponentScore"}),

        df_compact_season_results[["Season", "Divison", "LTeamID", "DayNum", "WScore", "LScore"]]
        .assign(Result="L")
        .rename(columns={"LTeamID": "TeamID", "LScore": "TeamScore", "WScore": "OpponentScore"}),
    ]
).reset_index(drop=True)

In [114]:
# Display Compact Season Results
df_team_compact_season_results

        Season Divison  TeamID  DayNum  TeamScore  OpponentScore Result
0         1985       M    1228      20         81             64      W
1         1985       M    1106      25         77             70      W
2         1985       M    1112      25         63             56      W
3         1985       M    1165      25         70             54      W
4         1985       M    1192      25         86             74      W
...        ...     ...     ...     ...        ...            ...    ...
659911    2025       W    3413     131         66             75      L
659912    2025       W    3476     132         49             66      L
659913    2025       W    3119     132         62             74      L
659914    2025       W    3125     132         62             83      L
659915    2025       W    3144     132         63             66      L

[659916 rows x 7 columns]

In [115]:
# Calculate the score difference for each game and add a new 'ScoreDifference' column
df_team_compact_season_results["ScoreDifference"] = df_team_compact_season_results["TeamScore"] - df_team_compact_season_results["OpponentScore"]

In [116]:
# Create a 'Win' column where 1 indicates a win and 0 indicates a loss
df_team_compact_season_results["Win"] = (df_team_compact_season_results["Result"] == "W").astype("int")

In [117]:
# # Display a few random samples from Compact Season Results after the change
df_team_compact_season_results.sample(10, random_state=100)

,Season,Divison,TeamID,DayNum,TeamScore,OpponentScore,Result,ScoreDifference,Win
111081,2010,M,1363,80,87,76,W,11,1
599920,2014,W,3409,36,43,81,L,-38,0
432896,2009,M,1383,11,61,88,L,-27,0
269593,2014,W,3278,26,79,55,W,24,1
297303,2019,W,3129,72,75,74,W,1,1
408983,2004,M,1175,26,54,63,L,-9,0
539720,2001,W,3156,129,63,65,L,-2,0
260192,2012,W,3376,58,62,58,W,4,1
554715,2005,W,3395,48,55,82,L,-27,0
44009,1996,M,1343,28,62,45,W,17,1

In [118]:
# Aggregate the team season data by Season, TeamID, and Division.
agg_team_season = (
    df_team_compact_season_results.groupby(["Season", "TeamID", "Divison"])
    .agg(
        TeamScore=("TeamScore", "sum"),
        OpponentScore=("OpponentScore", "sum"),
        ScoreDifference=("ScoreDifference", "sum"),
        AverageScoreDifference=("ScoreDifference", "mean"),
        MedianScoreDifference=("ScoreDifference", "median"),
        MinScoreDifference=("ScoreDifference", "min"),
        MaxScoreDifference=("ScoreDifference", "max"),
        Wins=("Win", "sum"),
        Losses=("Result", lambda x: (x == "L").sum()),
        WinPercentage=("Win", "mean"),
    )
    .reset_index()
)

In [119]:
# Display a few random samples from the Aggregated Season DataFrame
agg_team_season.sample(10, random_state=100)

,Season,TeamID,Divison,TeamScore,OpponentScore,ScoreDifference,AverageScoreDifference,MedianScoreDifference,MinScoreDifference,MaxScoreDifference,Wins,Losses,WinPercentage
1181,1989,1149,M,1791,1850,-59,-2.458333,-3.0,-35,20,8,16,0.333333
12007,2010,3132,W,2433,1984,449,13.606061,15.0,-19,35,27,6,0.818182
3914,1998,1199,M,2114,2048,66,2.200000,4.0,-48,38,17,13,0.566667
19911,2021,3388,W,1632,1859,-227,-8.730769,-9.5,-32,18,7,19,0.269231
16434,2016,3403,W,1963,2071,-108,-3.483871,-9.0,-39,62,13,18,0.419355
18843,2020,1358,M,2057,2021,36,1.333333,3.0,-16,20,14,13,0.518519
15678,2015,3347,W,1696,1796,-100,-3.448276,2.0,-36,24,17,12,0.586207
6360,2002,1143,M,2178,1992,186,6.200000,8.5,-46,33,22,8,0.733333
18715,2020,1227,M,2337,2335,2,0.058824,0.5,-46,34,17,17,0.500000
22658,2025,3254,W,1601,2025,-424,-14.133333,-11.5,-65,11,6,24,0.200000

In [120]:
# Adding a "HighSeed" column by extracting the numerical seed value (ignoring 'a' and 'b' suffixes) to represent team strength
df_seeds["HighSeed"] = (
    df_seeds["Seed"].str.replace("a", "").str.replace("b", "").str[1:].astype("int")
)

In [121]:
# Merge the "HighSeed" information from df_seeds into the aggregated team season data
agg_team_season = agg_team_season.merge(
    df_seeds, on=["Season", "TeamID", "Divison"], how="left"
)

In [122]:
# Display a few random samples from the Aggregated Season DataFrame after the change
agg_team_season.sample(10, random_state=100)

,Season,TeamID,Divison,TeamScore,OpponentScore,ScoreDifference,AverageScoreDifference,MedianScoreDifference,MinScoreDifference,MaxScoreDifference,Wins,Losses,WinPercentage,Seed,HighSeed
1181,1989,1149,M,1791,1850,-59,-2.458333,-3.0,-35,20,8,16,0.333333,NaN,NaN
12007,2010,3132,W,2433,1984,449,13.606061,15.0,-19,35,27,6,0.818182,Y12,12.0
3914,1998,1199,M,2114,2048,66,2.200000,4.0,-48,38,17,13,0.566667,Y12,12.0
19911,2021,3388,W,1632,1859,-227,-8.730769,-9.5,-32,18,7,19,0.269231,NaN,NaN
16434,2016,3403,W,1963,2071,-108,-3.483871,-9.0,-39,62,13,18,0.419355,NaN,NaN
18843,2020,1358,M,2057,2021,36,1.333333,3.0,-16,20,14,13,0.518519,NaN,NaN
15678,2015,3347,W,1696,1796,-100,-3.448276,2.0,-36,24,17,12,0.586207,NaN,NaN
6360,2002,1143,M,2178,1992,186,6.200000,8.5,-46,33,22,8,0.733333,Y06,6.0
18715,2020,1227,M,2337,2335,2,0.058824,0.5,-46,34,17,17,0.500000,NaN,NaN
22658,2025,3254,W,1601,2025,-424,-14.133333,-11.5,-65,11,6,24,0.200000,NaN,NaN

In [123]:
# Combining tournament results for both winners and losers into a single dataframe
# Each result is assigned a "GameResult" (W for winner, L for loser), and columns are renamed for consistency
df_team_tourney_results = pd.concat(
    [
        df_compact_tourney_results[
            ["Season", "Divison", "WTeamID", "LTeamID", "WScore", "LScore"]
        ]
        .assign(GameResult="W")
        .rename(
            columns={
                "WTeamID": "TeamID",
                "LTeamID": "OpponentTeamID",
                "WScore": "TeamScore",
                "LScore": "OpponentScore",
            }
        ),
        df_compact_tourney_results[
            ["Season", "Divison", "LTeamID", "WTeamID", "LScore", "WScore"]
        ]
        .assign(GameResult="L")
        .rename(
            columns={
                "LTeamID": "TeamID",
                "WTeamID": "OpponentTeamID",
                "LScore": "TeamScore",
                "WScore": "OpponentScore",
            }
        ),
    ]
).reset_index(drop=True)

In [124]:
# Creating a binary "Win" column where 1 represents a win and 0 represents a loss
df_team_tourney_results["Win"] = (df_team_tourney_results["GameResult"] == "W").astype(
    "int"
)

In [125]:
# Display a few random samples from the Tournament Results DataFrame after the changes
df_team_tourney_results.sample(10, random_state=100)

,Season,Divison,TeamID,OpponentTeamID,TeamScore,OpponentScore,GameResult,Win
7415,2009,W,3314,3345,70,85,L,0
1598,2010,M,1437,1352,73,70,W,1
2295,2021,M,1166,1325,72,58,W,1
1287,2005,M,1257,1418,68,62,W,1
3742,2017,W,3393,3235,85,65,W,1
4848,1995,M,1207,1314,64,74,L,0
7058,2003,W,3437,3397,49,73,L,0
5858,2011,M,1396,1361,64,71,L,0
1361,2006,M,1130,1285,69,56,W,1
5683,2008,M,1172,1242,57,59,L,0

In [126]:
# Merge tournament results with aggregated season data for both teams and opponents
## to add features like win percentage, median score difference, and high seed
### for both teams and their opponents

df_historic_tourney_features = df_team_tourney_results.merge(
    agg_team_season[
        ["Season", "Divison", "TeamID", "WinPercentage", "MedianScoreDifference", "HighSeed"]
    ],
    on=["Season", "Divison", "TeamID"],
    how="left",
).merge(
    agg_team_season[
        ["Season", "Divison", "TeamID", "WinPercentage", "MedianScoreDifference", "HighSeed"]
    ].rename(
        columns={
            "TeamID": "OpponentTeamID",
            "WinPercentage": "OpponentWinPercentage",
            "MedianScoreDifference": "OpponentMedianScoreDifference",
            "HighSeed": "OpponentHighSeed",
        }
    ),
    on=["Season", "Divison", "OpponentTeamID"],
)

In [127]:
# Display the Features DataFrame
df_historic_tourney_features

,Season,Divison,TeamID,OpponentTeamID,TeamScore,OpponentScore,GameResult,Win,WinPercentage,MedianScoreDifference,HighSeed,OpponentWinPercentage,OpponentMedianScoreDifference,OpponentHighSeed
0,1985,M,1116,1234,63,54,W,1,0.636364,5.0,9.0,0.666667,9.5,8.0
1,1985,M,1120,1345,59,58,W,1,0.620690,2.0,11.0,0.680000,9.0,6.0
2,1985,M,1207,1250,68,43,W,1,0.925926,14.0,1.0,0.379310,-3.0,16.0
3,1985,M,1229,1425,58,55,W,1,0.740741,6.0,9.0,0.678571,2.5,8.0
4,1985,M,1242,1325,49,38,W,1,0.766667,5.5,3.0,0.740741,6.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8331,2024,W,3425,3163,73,80,L,0,0.838710,9.0,1.0,0.848485,26.0,3.0
8332,2024,W,3261,3234,87,94,L,0,0.848485,23.0,3.0,0.878788,23.0,1.0
8333,2024,W,3163,3234,69,71,L,0,0.848485,26.0,3.0,0.878788,23.0,1.0
8334,2024,W,3301,3376,59,78,L,0,0.818182,12.0,3.0,1.000000,26.0,1.0
8335,2024,W,3234,3376,75,87,L,0,0.878788,23.0,1.0,1.000000,26.0,1.0

In [128]:
# Calculate feature differences between teams and their opponents

df_historic_tourney_features["WinPercentageDifference"] = (
    df_historic_tourney_features["WinPercentage"]
    - df_historic_tourney_features["OpponentWinPercentage"]
)

df_historic_tourney_features["HighSeedDifference"] = (
    df_historic_tourney_features["HighSeed"]
    - df_historic_tourney_features["OpponentHighSeed"]
)

df_historic_tourney_features["MedianScoreDifferenceDifference"] = (
    df_historic_tourney_features["MedianScoreDifference"]
    - df_historic_tourney_features["OpponentMedianScoreDifference"]
)

In [129]:
# Display the Features DataFrame after adding new features
df_historic_tourney_features.sample(10, random_state=100)

,Season,Divison,TeamID,OpponentTeamID,TeamScore,OpponentScore,GameResult,Win,WinPercentage,MedianScoreDifference,HighSeed,OpponentWinPercentage,OpponentMedianScoreDifference,OpponentHighSeed,WinPercentageDifference,HighSeedDifference,MedianScoreDifferenceDifference
7415,2009,W,3314,3345,70,85,L,0,0.812500,14.5,3.0,0.687500,11.0,6.0,0.125000,-3.0,3.5
1598,2010,M,1437,1352,73,70,W,1,0.774194,8.0,2.0,0.676471,5.5,15.0,0.097723,-13.0,2.5
2295,2021,M,1166,1325,72,58,W,1,0.714286,6.0,5.0,0.681818,9.0,13.0,0.032468,-8.0,-3.0
1287,2005,M,1257,1418,68,62,W,1,0.870968,15.0,4.0,0.655172,7.0,13.0,0.215795,-9.0,8.0
3742,2017,W,3393,3235,85,65,W,1,0.677419,16.0,8.0,0.600000,7.0,9.0,0.077419,-1.0,9.0
4848,1995,M,1207,1314,64,74,L,0,0.678571,4.5,6.0,0.827586,10.0,2.0,-0.149015,4.0,-5.5
7058,2003,W,3437,3397,49,73,L,0,0.833333,10.0,2.0,0.870968,16.0,1.0,-0.037634,1.0,-6.0
5858,2011,M,1396,1361,64,71,L,0,0.781250,9.5,7.0,0.937500,12.5,2.0,-0.156250,5.0,-3.0
1361,2006,M,1130,1285,69,56,W,1,0.781250,6.0,4.0,0.777778,6.0,12.0,0.003472,-8.0,0.0
5683,2008,M,1172,1242,57,59,L,0,0.806452,13.0,10.0,0.909091,19.0,1.0,-0.102639,9.0,-6.0

In [130]:
# Display the 538 Ratings DataFrame
fivethiryeight_scores

     Season  TeamID                TeamName  538rating Divison
0      2016    1242                  Kansas      94.46       M
1      2016    1314          North Carolina      93.94       M
2      2016    1438                Virginia      92.46       M
3      2016    1277          Michigan State      91.84       M
4      2016    1328                Oklahoma      89.96       M
..      ...     ...                     ...        ...     ...
927    2023    3368  Southeastern Louisiana      66.27       W
928    2023    3151             Chattanooga      64.87       W
929    2023    3284                Monmouth      64.10       W
930    2023    3380                Southern      61.73       W
931    2023    3357            Sacred Heart      59.94       W

[932 rows x 5 columns]

In [131]:
# Merge 538 ratings for teams and their opponents into the tournament features
# Remove the "TeamName" column and handle missing values for 538 ratings

# Drop "TeamName" column before merging
fivethiryeight_scores_cleaned = fivethiryeight_scores.drop("TeamName", axis=1)

# Merge team 538 ratings
df_historic_tourney_features = df_historic_tourney_features.merge(
    fivethiryeight_scores_cleaned,
    on=["Season", "Divison", "TeamID"],
    how="left",
).dropna(subset=["538rating"])

# Merge opponent 538 ratings
df_historic_tourney_features = df_historic_tourney_features.merge(
    fivethiryeight_scores_cleaned.rename(
        columns={"TeamID": "OpponentTeamID"}
    ),
    on=["Season", "Divison", "OpponentTeamID"],
    how="left",
    suffixes=("", "Opponent"),
).dropna(subset=["538ratingOpponent"])

In [132]:
# Display the Features DataFrame after adding the 538 features
df_historic_tourney_features.sample(10, random_state=100)

,Season,Divison,TeamID,OpponentTeamID,TeamScore,OpponentScore,GameResult,Win,WinPercentage,MedianScoreDifference,HighSeed,OpponentWinPercentage,OpponentMedianScoreDifference,OpponentHighSeed,WinPercentageDifference,HighSeedDifference,MedianScoreDifferenceDifference,538rating,538ratingOpponent
1130,2019,M,1125,1268,77,79,L,0,0.833333,12.5,11.0,0.687500,8.0,6.0,0.145833,5.0,4.5,81.74,84.82
969,2016,M,1268,1242,63,79,L,0,0.750000,6.5,5.0,0.878788,10.0,1.0,-0.128788,4.0,-3.5,87.37,94.46
1273,2022,M,1168,1181,61,78,L,0,0.655172,3.0,15.0,0.823529,11.5,2.0,-0.168357,13.0,-8.5,71.78,89.28
28,2016,M,1372,1452,70,56,W,1,0.821429,20.5,14.0,0.764706,11.0,3.0,0.056723,11.0,9.5,80.98,89.30
1292,2022,M,1350,1344,51,79,L,0,0.657143,5.0,12.0,0.833333,5.0,4.0,-0.176190,8.0,0.0,79.91,82.72
874,2023,W,3195,3450,74,63,W,1,0.909091,19.0,12.0,0.696970,7.0,5.0,0.212121,7.0,12.0,82.94,86.55
1080,2018,M,1252,1314,66,84,L,0,0.689655,7.0,15.0,0.714286,8.0,2.0,-0.024631,13.0,-1.0,72.45,90.62
1818,2023,W,3195,3437,57,76,L,0,0.909091,19.0,12.0,0.823529,13.0,4.0,0.085561,8.0,6.0,82.94,88.55
911,2023,W,3261,3274,54,42,W,1,0.933333,22.0,3.0,0.612903,5.0,9.0,0.320430,-6.0,17.0,96.14,83.49
1216,2021,M,1438,1325,58,62,L,0,0.750000,8.5,4.0,0.681818,9.0,13.0,0.068182,-9.0,-0.5,88.06,77.51

In [133]:
# Calculate the difference in 538 ratings between teams and their opponents
df_historic_tourney_features["538rating_Difference"] = (
    df_historic_tourney_features["538rating"]
    - df_historic_tourney_features["538ratingOpponent"]
)

In [134]:
# Display a few random samples from the Features DataFrame after adding new features
df_historic_tourney_features.sample(10, random_state=100)

,Season,Divison,TeamID,OpponentTeamID,TeamScore,OpponentScore,GameResult,Win,WinPercentage,MedianScoreDifference,HighSeed,OpponentWinPercentage,OpponentMedianScoreDifference,OpponentHighSeed,WinPercentageDifference,HighSeedDifference,MedianScoreDifferenceDifference,538rating,538ratingOpponent,538rating_Difference
1130,2019,M,1125,1268,77,79,L,0,0.833333,12.5,11.0,0.687500,8.0,6.0,0.145833,5.0,4.5,81.74,84.82,-3.08
969,2016,M,1268,1242,63,79,L,0,0.750000,6.5,5.0,0.878788,10.0,1.0,-0.128788,4.0,-3.5,87.37,94.46,-7.09
1273,2022,M,1168,1181,61,78,L,0,0.655172,3.0,15.0,0.823529,11.5,2.0,-0.168357,13.0,-8.5,71.78,89.28,-17.50
28,2016,M,1372,1452,70,56,W,1,0.821429,20.5,14.0,0.764706,11.0,3.0,0.056723,11.0,9.5,80.98,89.30,-8.32
1292,2022,M,1350,1344,51,79,L,0,0.657143,5.0,12.0,0.833333,5.0,4.0,-0.176190,8.0,0.0,79.91,82.72,-2.81
874,2023,W,3195,3450,74,63,W,1,0.909091,19.0,12.0,0.696970,7.0,5.0,0.212121,7.0,12.0,82.94,86.55,-3.61
1080,2018,M,1252,1314,66,84,L,0,0.689655,7.0,15.0,0.714286,8.0,2.0,-0.024631,13.0,-1.0,72.45,90.62,-18.17
1818,2023,W,3195,3437,57,76,L,0,0.909091,19.0,12.0,0.823529,13.0,4.0,0.085561,8.0,6.0,82.94,88.55,-5.61
911,2023,W,3261,3274,54,42,W,1,0.933333,22.0,3.0,0.612903,5.0,9.0,0.320430,-6.0,17.0,96.14,83.49,12.65
1216,2021,M,1438,1325,58,62,L,0,0.750000,8.5,4.0,0.681818,9.0,13.0,0.068182,-9.0,-0.5,88.06,77.51,10.55

In [135]:
# Display only 538 related features
df_historic_tourney_features[["Season", "TeamID", "538rating", "538ratingOpponent", "538rating_Difference"]].sample(10, random_state=100)

      Season  TeamID  538rating  538ratingOpponent  538rating_Difference
1130    2019    1125      81.74              84.82                 -3.08
969     2016    1268      87.37              94.46                 -7.09
1273    2022    1168      71.78              89.28                -17.50
28      2016    1372      80.98              89.30                 -8.32
1292    2022    1350      79.91              82.72                 -2.81
874     2023    3195      82.94              86.55                 -3.61
1080    2018    1252      72.45              90.62                -18.17
1818    2023    3195      82.94              88.55                 -5.61
911     2023    3261      96.14              83.49                 12.65
1216    2021    1438      88.06              77.51                 10.55

In [136]:
# Display first few samples from the Features DataFrame
df_historic_tourney_features.head()

,Season,Divison,TeamID,OpponentTeamID,TeamScore,OpponentScore,GameResult,Win,WinPercentage,MedianScoreDifference,HighSeed,OpponentWinPercentage,OpponentMedianScoreDifference,OpponentHighSeed,WinPercentageDifference,HighSeedDifference,MedianScoreDifferenceDifference,538rating,538ratingOpponent,538rating_Difference
0,2016,M,1195,1192,96,65,W,1,0.551724,2.0,16.0,0.548387,2.0,16.0,0.003337,0.0,0.0,71.41,66.72,4.69
1,2016,M,1455,1435,70,50,W,1,0.741935,17.0,11.0,0.593750,10.0,11.0,0.148185,0.0,7.0,86.59,85.59,1.00
2,2016,M,1221,1380,59,55,W,1,0.424242,-4.0,16.0,0.612903,4.0,16.0,-0.188661,0.0,-8.0,66.85,67.96,-1.11
3,2016,M,1276,1409,67,62,W,1,0.636364,5.0,11.0,0.645161,8.0,11.0,-0.008798,0.0,-3.0,79.57,79.93,-0.36
4,2016,M,1114,1345,85,83,W,1,0.870968,8.0,12.0,0.764706,13.0,5.0,0.106262,7.0,-5.0,78.90,88.68,-9.78

In [137]:
# Create a baseline prediction based on team and opponent seed rankings

# If the team's seed is higher than the opponent's, assign True to BaselinePred
df_historic_tourney_features["BaselinePred"] = (
    df_historic_tourney_features["HighSeed"]
    < df_historic_tourney_features["OpponentHighSeed"]
)

# If seeds are equal, compare win percentages to set the BaselinePred value
df_historic_tourney_features.loc[
    df_historic_tourney_features["HighSeed"]
    == df_historic_tourney_features["OpponentHighSeed"],
    "BaselinePred",
] = (
    df_historic_tourney_features["WinPercentage"]
    > df_historic_tourney_features["OpponentWinPercentage"]
)

In [138]:
# Display first few samples from the Features DataFrame after adding BaselinePred
df_historic_tourney_features.head()

,Season,Divison,TeamID,OpponentTeamID,TeamScore,OpponentScore,GameResult,Win,WinPercentage,MedianScoreDifference,...,OpponentWinPercentage,OpponentMedianScoreDifference,OpponentHighSeed,WinPercentageDifference,HighSeedDifference,MedianScoreDifferenceDifference,538rating,538ratingOpponent,538rating_Difference,BaselinePred
0,2016,M,1195,1192,96,65,W,1,0.551724,2.0,...,0.548387,2.0,16.0,0.003337,0.0,0.0,71.41,66.72,4.69,True
1,2016,M,1455,1435,70,50,W,1,0.741935,17.0,...,0.593750,10.0,11.0,0.148185,0.0,7.0,86.59,85.59,1.00,True
2,2016,M,1221,1380,59,55,W,1,0.424242,-4.0,...,0.612903,4.0,16.0,-0.188661,0.0,-8.0,66.85,67.96,-1.11,False
3,2016,M,1276,1409,67,62,W,1,0.636364,5.0,...,0.645161,8.0,11.0,-0.008798,0.0,-3.0,79.57,79.93,-0.36,False
4,2016,M,1114,1345,85,83,W,1,0.870968,8.0,...,0.764706,13.0,5.0,0.106262,7.0,-5.0,78.90,88.68,-9.78,False

In [139]:
from sklearn.metrics import accuracy_score, log_loss
import pandas as pd

cv_scores_baseline = []
log_losses_baseline = []
seasons = []

# Loop through each season to calculate the metrics
for season in df_historic_tourney_features["Season"].unique():
    pred = df_historic_tourney_features.query("Season == @season")[
        "BaselinePred"
    ].astype("int")  # Baseline predictions for the current season

    y = df_historic_tourney_features.query("Season == @season")["Win"]  # Actual results

    # Calculate accuracy and log loss for the current season
    score = accuracy_score(y, pred)
    score_ll = log_loss(y, pred)

    # Store the accuracy, log loss, and season
    cv_scores_baseline.append(score)
    log_losses_baseline.append(score_ll)
    seasons.append(season)

# Create a DataFrame to display the results
results_df = pd.DataFrame({
    'Season': seasons,
    'Accuracy': cv_scores_baseline,
    'Log Loss': log_losses_baseline
})

# Display the DataFrame
display(results_df)

# Print the overall average accuracy across all seasons
print(f"\nBaseline accuracy: {np.mean(cv_scores_baseline):0.4f}")

   Season  Accuracy   Log Loss
0    2016  0.684615  11.367614
1    2017  0.776923   8.040507
2    2018  0.700000  10.813096
3    2019  0.753846   8.872284
4    2021  0.751938   8.941061
5    2022  0.701493  10.759300
6    2023  0.716418  10.221335

Baseline accuracy: 0.7265

In [140]:
# Combine Teams data
df_all_teams = pd.concat(
    [
        pd.read_csv("raw/MTeams.csv").assign(Divison="M"),
        pd.read_csv("raw/WTeams.csv").assign(Divison="W"),
    ]
).reset_index(drop=True).drop_duplicates()

# Create a cross join to produce every possible pair
df_all_teams['key'] = 1
df_team_pairs = df_all_teams[['TeamID', 'Divison', 'key']].merge(
    df_all_teams[['TeamID', 'Divison', 'key']],
    on='key',
    suffixes=('', 'Opponent')
).query("TeamID != TeamIDOpponent").drop('key', axis=1)

df_team_pairs.rename(columns={"TeamIDOpponent": "OpponentTeamID"}, inplace=True)

# Remove pairs where TeamID > OpponentTeamID
df_team_pairs = df_team_pairs[df_team_pairs["TeamID"] < df_team_pairs["OpponentTeamID"]].copy()

# Add Season and Matchup
df_team_pairs['Season'] = 2025
df_team_pairs['Matchup'] = (
    df_team_pairs['Season'].astype(str) + "_" +
    df_team_pairs['TeamID'].astype(str) + "_" +
    df_team_pairs['OpponentTeamID'].astype(str)
)

In [141]:
display(df_team_pairs[["TeamID", "OpponentTeamID", "Season", "Matchup"]])

        TeamID  OpponentTeamID  Season         Matchup
1         1101            1102    2025  2025_1101_1102
2         1101            1103    2025  2025_1101_1103
3         1101            1104    2025  2025_1101_1104
4         1101            1105    2025  2025_1101_1105
5         1101            1106    2025  2025_1101_1106
...        ...             ...     ...             ...
572288    3477            3479    2025  2025_3477_3479
572289    3477            3480    2025  2025_3477_3480
573046    3478            3479    2025  2025_3478_3479
573047    3478            3480    2025  2025_3478_3480
573805    3479            3480    2025  2025_3479_3480

[286903 rows x 4 columns]

In [142]:
# Merge for "TeamID"
df_team_pairs = df_team_pairs.merge(
    agg_team_season[
        ["Season", "Divison", "TeamID", "WinPercentage", "MedianScoreDifference", "HighSeed"]
    ],
    on=["Season", "Divison", "TeamID"],
    how="left"
)

# Merge for "OpponentTeamID"
df_team_pairs = df_team_pairs.merge(
    agg_team_season[
        ["Season", "Divison", "TeamID", "WinPercentage", "MedianScoreDifference", "HighSeed"]
    ].rename(columns={
        "TeamID": "OpponentTeamID",
        "WinPercentage": "OpponentWinPercentage",
        "MedianScoreDifference": "OpponentMedianScoreDifference",
        "HighSeed": "OpponentHighSeed"
    }),
    on=["Season", "Divison", "OpponentTeamID"],
    how="left"
).reset_index(drop=True)

# Remove irrelevant columns
df_team_pairs = df_team_pairs[
    [
        "TeamID",
        "HighSeed",
        "OpponentTeamID",
        "OpponentHighSeed",
        "Season",
        "Matchup",
        "WinPercentage",
        "MedianScoreDifference",
        "OpponentWinPercentage",
        "OpponentMedianScoreDifference"
    ]
]

In [143]:
display(df_team_pairs)

,TeamID,HighSeed,OpponentTeamID,OpponentHighSeed,Season,Matchup,WinPercentage,MedianScoreDifference,OpponentWinPercentage,OpponentMedianScoreDifference
0,1101,NaN,1102,NaN,2025,2025_1101_1102,0.448276,-2.0,0.125000,-10.0
1,1101,NaN,1103,13.0,2025,2025_1101_1103,0.448276,-2.0,0.812500,9.5
2,1101,NaN,1104,2.0,2025,2025_1101_1104,0.448276,-2.0,0.757576,7.0
3,1101,NaN,1105,NaN,2025,2025_1101_1105,0.448276,-2.0,0.241379,-10.0
4,1101,NaN,1106,16.0,2025,2025_1101_1106,0.448276,-2.0,0.545455,1.0
...,...,...,...,...,...,...,...,...,...,...
286898,3477,NaN,3479,NaN,2025,2025_3477_3479,0.185185,-11.0,0.250000,-7.5
286899,3477,NaN,3480,NaN,2025,2025_3477_3480,0.185185,-11.0,0.392857,-6.5
286900,3478,NaN,3479,NaN,2025,2025_3478_3479,0.225806,-16.0,0.250000,-7.5
286901,3478,NaN,3480,NaN,2025,2025_3478_3480,0.225806,-16.0,0.392857,-6.5
286902,3479,NaN,3480,NaN,2025,2025_3479_3480,0.250000,-7.5,0.392857,-6.5

In [144]:
# Aggregate 538 ratings
agg_538 = (
    fivethiryeight_scores_cleaned.groupby(["TeamID", "Divison"])
    .agg(
        Average538rating=("538rating", "mean"),
    )
    .reset_index()
)

In [145]:
display(agg_538)

     TeamID Divison  Average538rating
0      1101       M         74.685000
1      1103       M         76.690000
2      1104       M         87.212500
3      1111       M         70.280000
4      1112       M         89.162000
..      ...     ...               ...
357    3450       W         83.646667
358    3452       W         86.200000
359    3453       W         85.216667
360    3460       W         75.225000
361    3461       W         72.710000

[362 rows x 3 columns]

In [146]:
# Merge 538 rating scores for TeamID
df_team_pairs = df_team_pairs.merge(
    agg_538,
    on=["TeamID"],
    how="left",
)

# Merge 538 rating scores for OpponentTeamID
df_team_pairs = df_team_pairs.merge(
    agg_538.rename(
        columns={"TeamID": "OpponentTeamID"}
    ),
    on=["OpponentTeamID"],
    how="left",
    suffixes=("", "Opponent"),
)

In [147]:
display(df_team_pairs)

,TeamID,HighSeed,OpponentTeamID,OpponentHighSeed,Season,Matchup,WinPercentage,MedianScoreDifference,OpponentWinPercentage,OpponentMedianScoreDifference,Divison,Average538rating,DivisonOpponent,Average538ratingOpponent
0,1101,NaN,1102,NaN,2025,2025_1101_1102,0.448276,-2.0,0.125000,-10.0,M,74.685,NaN,NaN
1,1101,NaN,1103,13.0,2025,2025_1101_1103,0.448276,-2.0,0.812500,9.5,M,74.685,M,76.6900
2,1101,NaN,1104,2.0,2025,2025_1101_1104,0.448276,-2.0,0.757576,7.0,M,74.685,M,87.2125
3,1101,NaN,1105,NaN,2025,2025_1101_1105,0.448276,-2.0,0.241379,-10.0,M,74.685,NaN,NaN
4,1101,NaN,1106,16.0,2025,2025_1101_1106,0.448276,-2.0,0.545455,1.0,M,74.685,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286898,3477,NaN,3479,NaN,2025,2025_3477_3479,0.185185,-11.0,0.250000,-7.5,NaN,NaN,NaN,NaN
286899,3477,NaN,3480,NaN,2025,2025_3477_3480,0.185185,-11.0,0.392857,-6.5,NaN,NaN,NaN,NaN
286900,3478,NaN,3479,NaN,2025,2025_3478_3479,0.225806,-16.0,0.250000,-7.5,NaN,NaN,NaN,NaN
286901,3478,NaN,3480,NaN,2025,2025_3478_3480,0.225806,-16.0,0.392857,-6.5,NaN,NaN,NaN,NaN
286902,3479,NaN,3480,NaN,2025,2025_3479_3480,0.250000,-7.5,0.392857,-6.5,NaN,NaN,NaN,NaN

In [149]:
# Fill High before Feature Calculations
for col in df_team_pairs.columns:
    if col in ["HighSeed", "OpponentHighSeed"]:
        df_team_pairs[col] = df_team_pairs[col].fillna(17)
    if col in ["Average538rating", "Average538ratingOpponent"]:
        df_team_pairs[col] = df_team_pairs[col].fillna(50)

In [150]:
display(df_team_pairs)

,TeamID,HighSeed,OpponentTeamID,OpponentHighSeed,Season,Matchup,WinPercentage,MedianScoreDifference,OpponentWinPercentage,OpponentMedianScoreDifference,Divison,Average538rating,DivisonOpponent,Average538ratingOpponent
0,1101,17.0,1102,17.0,2025,2025_1101_1102,0.448276,-2.0,0.125000,-10.0,M,74.685,NaN,50.0000
1,1101,17.0,1103,13.0,2025,2025_1101_1103,0.448276,-2.0,0.812500,9.5,M,74.685,M,76.6900
2,1101,17.0,1104,2.0,2025,2025_1101_1104,0.448276,-2.0,0.757576,7.0,M,74.685,M,87.2125
3,1101,17.0,1105,17.0,2025,2025_1101_1105,0.448276,-2.0,0.241379,-10.0,M,74.685,NaN,50.0000
4,1101,17.0,1106,16.0,2025,2025_1101_1106,0.448276,-2.0,0.545455,1.0,M,74.685,NaN,50.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286898,3477,17.0,3479,17.0,2025,2025_3477_3479,0.185185,-11.0,0.250000,-7.5,NaN,50.000,NaN,50.0000
286899,3477,17.0,3480,17.0,2025,2025_3477_3480,0.185185,-11.0,0.392857,-6.5,NaN,50.000,NaN,50.0000
286900,3478,17.0,3479,17.0,2025,2025_3478_3479,0.225806,-16.0,0.250000,-7.5,NaN,50.000,NaN,50.0000
286901,3478,17.0,3480,17.0,2025,2025_3478_3480,0.225806,-16.0,0.392857,-6.5,NaN,50.000,NaN,50.0000
286902,3479,17.0,3480,17.0,2025,2025_3479_3480,0.250000,-7.5,0.392857,-6.5,NaN,50.000,NaN,50.0000

In [ ]:
####################################### READ ##############################################
############## IF RUNNING THIS THEN REPLACE MY EMAIL AND USERNAME WITH YOURS ##############
### ALSO U NEED A TEXT FILE OF YOUR TOKEN NAMED "github_token.txt" INSIDE OF YOUR DRIVE ###
####################################### READ ##############################################

# Read the token from Drive
from google.colab import drive
drive.mount('/content/drive')
with open('/content/drive/My Drive/github_token.txt') as f:
    token = f.read().strip()

# Git Config
!git config --global user.email "rajaropen@gmail.com"
!git config --global user.name "NeedRam"

# Clone repo
repo_url = f"https://{token}@github.com/jamie07262/INFO-3608-PROJECT.git"
!git clone {repo_url}

# Save the Features Table to a CSV file
df_historic_tourney_features.to_csv("Features.csv", index=False)

# Move the processed to the repo
import shutil
shutil.move("Features.csv", "INFO-3608-PROJECT/data/processed/Features.csv")

# Commit and push the change
%cd INFO-3608-PROJECT
!git add data/processed/Features.csv
!git commit -m "Add processed data Features CSV"
!git push

Mounted at /content/drive
Cloning into 'INFO-3608-PROJECT'...
remote: Enumerating objects: 166, done.
remote: Counting objects: 100% (166/166), done.
remote: Compressing objects: 100% (153/153), done.
remote: Total 166 (delta 67), reused 63 (delta 9), pack-reused 0 (from 0)
Receiving objects: 100% (166/166), 34.63 MiB | 14.35 MiB/s, done.
Resolving deltas: 100% (67/67), done.
Updating files: 100% (52/52), done.
/content/INFO-3608-PROJECT
[main e8cef64] Add processed data Features CSV
 1 file changed, 1835 insertions(+)
 create mode 100644 data/processed/Features.csv
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 2 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (4/4), 376 bytes | 376.00 KiB/s, done.
Total 4 (delta 2), reused 3 (delta 2), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/jamie07262/INFO-3608-PROJECT.git
   4176cc2..e8cef64  main -> main